// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-smX4x2KcikWl8LxZGcyhRb3-YX1xI-I',
    appId: '1:398602524498:web:b22cc25e3d89b8a23d8c8b',
    messagingSenderId: '398602524498',
    projectId: 'neighbornexus-aaf99',
    authDomain: 'neighbornexus-aaf99.firebaseapp.com',
    storageBucket: 'neighbornexus-aaf99.appspot.com',
    measurementId: 'G-Q72TEZ2Y8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Ebfm6UB0fMsEbVOKW53Ow3aom73TBfU',
    appId: '1:398602524498:android:fe22be73cdd2ad123d8c8b',
    messagingSenderId: '398602524498',
    projectId: 'neighbornexus-aaf99',
    storageBucket: 'neighbornexus-aaf99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaGQm46o0m8mr_os66sEtLkJDlzV1WsaI',
    appId: '1:398602524498:ios:d94fa19d80afdb2a3d8c8b',
    messagingSenderId: '398602524498',
    projectId: 'neighbornexus-aaf99',
    storageBucket: 'neighbornexus-aaf99.appspot.com',
    iosBundleId: 'com.example.neighborNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaGQm46o0m8mr_os66sEtLkJDlzV1WsaI',
    appId: '1:398602524498:ios:a0b72c351e2de9d23d8c8b',
    messagingSenderId: '398602524498',
    projectId: 'neighbornexus-aaf99',
    storageBucket: 'neighbornexus-aaf99.appspot.com',
    iosBundleId: 'com.example.neighborNexus.RunnerTests',
  );
}
