// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAptnLl9irzllOjL0ZtOAQSFD-_eWNhCGA',
    appId: '1:653495789040:web:2bd7d9d13d6968d4c3a935',
    messagingSenderId: '653495789040',
    projectId: 'neighborhoodnexus-4247a',
    authDomain: 'neighborhoodnexus-4247a.firebaseapp.com',
    storageBucket: 'neighborhoodnexus-4247a.appspot.com',
    measurementId: 'G-WZC3KLH642',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM9L49xf0oHyvhRmKFOttHBuqnko95aV0',
    appId: '1:653495789040:android:bf2ad8225fc7a7bcc3a935',
    messagingSenderId: '653495789040',
    projectId: 'neighborhoodnexus-4247a',
    storageBucket: 'neighborhoodnexus-4247a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVNRhN1TzqA4T16MAzWWLFydAh1QZSWU',
    appId: '1:653495789040:ios:57a83a9a98a26064c3a935',
    messagingSenderId: '653495789040',
    projectId: 'neighborhoodnexus-4247a',
    storageBucket: 'neighborhoodnexus-4247a.appspot.com',
    iosBundleId: 'com.example.neighborNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIVNRhN1TzqA4T16MAzWWLFydAh1QZSWU',
    appId: '1:653495789040:ios:595dbe3528d7c333c3a935',
    messagingSenderId: '653495789040',
    projectId: 'neighborhoodnexus-4247a',
    storageBucket: 'neighborhoodnexus-4247a.appspot.com',
    iosBundleId: 'com.example.neighborNexus.RunnerTests',
  );
}
