// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVbBH_FMPUUUGCAaJUhfbDvaDcqJyuX0',
    appId: '1:945595306234:web:8fb01a2542107f6d5bf943',
    messagingSenderId: '945595306234',
    projectId: 'neighborhoodnexus-57ac2',
    authDomain: 'neighborhoodnexus-57ac2.firebaseapp.com',
    storageBucket: 'neighborhoodnexus-57ac2.appspot.com',
    measurementId: 'G-KFDYV46MX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAW17Mv70EvT4r7lInFbapInVwOfwlo8I',
    appId: '1:945595306234:android:1d8871aec2bf77495bf943',
    messagingSenderId: '945595306234',
    projectId: 'neighborhoodnexus-57ac2',
    storageBucket: 'neighborhoodnexus-57ac2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCHgPUbksazr0PNvDTe9zePSRGKRxd8lc',
    appId: '1:945595306234:ios:de585ad5f6bcf6795bf943',
    messagingSenderId: '945595306234',
    projectId: 'neighborhoodnexus-57ac2',
    storageBucket: 'neighborhoodnexus-57ac2.appspot.com',
    iosBundleId: 'com.example.neighborNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCHgPUbksazr0PNvDTe9zePSRGKRxd8lc',
    appId: '1:945595306234:ios:d48727152e2acd815bf943',
    messagingSenderId: '945595306234',
    projectId: 'neighborhoodnexus-57ac2',
    storageBucket: 'neighborhoodnexus-57ac2.appspot.com',
    iosBundleId: 'com.example.neighborNexus.RunnerTests',
  );
}
